language: c
sudo: false

addons:
  apt:
    packages:
    - aspcud
    - libglpk-dev

before_install:
    - bash -exu .travis-ci.sh prepare
install:
    - bash -exu .travis-ci.sh install

cache:
    directories:
    - $HOME/.opam.cached
    - $HOME/local

script:
    - bash -exu .travis-ci.sh build

matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.06.1
      stage: Build
    - os: osx
      env: OCAML_VERSION=4.06.1 OPAM_TEST=1
      stage: Test
