# NB If minimum OCaml version for Dune changes, update DUNE_SECONDARY in configure.ac
URL_dune-local = https://github.com/ocaml/dune/releases/download/3.10.0/dune-3.10.0.tbz
MD5_dune-local = ebf73b21fc7154f8de3ac8e31667aa99
