name: Builds, tests & co

on: [ push, pull_request ]

env:
  OPAMBSVERSION: 2.1.0-beta4
  OPAMBSROOT: ~/.cache/.opam.cached
  OPAM12CACHE: ~/.cache/opam1.2/cache
  # This should be identical to the value in appveyor.yml
  OPAM_TEST_REPO_SHA: b02110b549a0b5275806ce27444fabac71093a0e
  OPAM_REPO_SHA: b02110b549a0b5275806ce27444fabac71093a0e
  # Default ocaml version for some jobs
  OCAML_VERSION: 4.11.2
  ## variables for cache paths
  GH_OCAML_CACHE: ~/.cache/ocaml-local/**

defaults:
  run:
    shell: bash

jobs:

####
# Opam tests
####
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ocamlv: [ 4.11.2 ]
      fail-fast: false
    env:
      OPAM_TEST: 1
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install bubblewrap
    - name: ocaml ${{ matrix.ocamlv }} cache - test
      id: ocaml-cache-test
      uses: actions/cache@v2
      with:
        path: ${{ env.GH_OCAML_CACHE }}
        key: ${{ runner.os }}-ocaml-${{ matrix.ocamlv }}-${{ hashFiles ('.github/scripts/ocaml-cache.sh', '.github/scripts/preamble.sh') }}-test
    - name: Building ocaml ${{ env.OCAML_VERSION }} cache - test
      if: steps.ocaml-cache-test.outputs.cache-hit != 'true'
      env:
        OCAML_VERSION: ${{ matrix.ocamlv }}
      run: bash -exu .github/scripts/ocaml-cache.sh ocaml
    - name: opam bootstrap cache
      id: opam-bootstrap
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.OPAMBSROOT }}/**
          ~/.cache/opam-local/bin/**
        key: opam-${{ runner.os }}-${{ env.OPAMBSVERSION }}-${{ matrix.ocamlv }}-${{ env.OPAM_REPO_SHA }}-${{ hashFiles ('.github/scripts/opam-bs-cache.sh', '.github/scripts/preamble.sh') }}
    - name: opam root cache
      if: steps.opam-bootstrap.outputs.cache-hit != 'true'
      run: bash -exu .github/scripts/opam-bs-cache.sh
    - name: opam-rt cache
      id: opam-rt
      uses: actions/cache@v2
      with:
        path: ~/.cache/opam-rt/**
        key: ${{ runner.os }}-opam-rt-${{ matrix.ocamlv }}
    - name: Test
      env:
        OCAML_VERSION: ${{ matrix.ocamlv }}
      run: bash -exu .github/scripts/main.sh
