name: Builds, tests & co

on: [ push, pull_request ]

env:
  OPAMBSVERSION: 2.1.0-beta4
  OPAMBSROOT: ~/.cache/.opam.cached
  OPAM12CACHE: ~/.cache/opam1.2/cache
  # This should be identical to the value in appveyor.yml
  OPAM_TEST_REPO_SHA: b02110b549a0b5275806ce27444fabac71093a0e
  OPAM_REPO_SHA: b02110b549a0b5275806ce27444fabac71093a0e
  # Default ocaml version for some jobs
  OCAML_VERSION: 4.11.2
  ## variables for cache paths
  GH_OCAML_CACHE: ~/.cache/ocaml-local/**
  SOLVER:

defaults:
  run:
    shell: bash

jobs:

####
# Test some conf packages
####
  depexts:
#    needs: [build]
    runs-on: ubuntu-latest
    name: external dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: depexts actions alpine 
        uses: ./ # Uses an action in the root directory
        id: depext-actions-alpine
