name: Opam

on: [push, pull_request]

env:
  COMMIT_RANGE: ${{ github.event.before }}...${{ github.event.after }}

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        cyg-root: [cygwin64]
        cyg-arch: [x86_64]
        git-for-windows: [0]
        dep-mode: [lib-ext]
        ocaml-port: ["", msvc, msvc64, mingw, mingw64]
        include:
          - ocaml-port: ""
            cyg-root: cygwin
            cyg-arch: x86
          - ocaml-port: msvc
            dep-mode: lib-pkg
            git-for-windows: 1
          - ocaml-port: mingw64
            dep-mode: lib-pkg
            git-for-windows: 1
    env:
      CYG_ROOT: ${{ matrix.cyg-root }}
      CYG_ARCH: ${{ matrix.cyg-arch }}
      OCAML_PORT: ${{ matrix.ocaml-port }}
      DEP_MODE: ${{ matrix.dep-mode }}
      GIT_FOR_WINDOWS: ${{ matrix.git-for-windows }}
      CYG_CACHE: C:/cygwin/var/cache/setup
      CYG_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE\\bootstrap
          key: never-flush-cache
      - uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE\\src_ext\\archives
          key: never-flush-cache

      - name: Opam install
        run: call "%GITHUB_WORKSPACE%\tests\ci\windows_build.cmd" install
      - name: Opam build
        run: call "%GITHUB_WORKSPACE%\tests\ci\windows_build.cmd" build
      - name: Opam test
        run: call "%GITHUB_WORKSPACE%\tests\ci\windows_build.cmd" test
