name: Builds, tests & co

on:
  push:
    paths:
    - 'src/**'
    - '!src/tools/**'
    - 'src_ext/**'
    - 'dune'
    - 'dune-project'
    - '*.opam'
    - 'Makefile*'
    - 'configure*'
  pull_request:
    paths:
    - 'src/**'
    - '!src/tools/**'
    - 'src_ext/**'
    - 'dune'
    - 'dune-project'
    - '*.opam'
    - 'Makefile*'
    - 'configure*'
    - '.github/scripts/**'
    - '.github/workflows/main.yml'
    - 'tests/**'
    - '!tests/bench/**'
    - 'shell/'
#    paths-ignore:
#    - 'release/**'
#    - 'shell/**'
#    - 'admin-scripts/**'
#    - 'doc/**'
#    - 'CHANGES'
#    - 'LICENSE'
#    - 'CONTRIBUTING.md'
#    - 'master_changes.md'
#    - 'README.md'

env:
  OPAMBSVERSION: 2.1.0
  OPAMBSROOT: ~/.cache/.opam.cached
  OPAM12CACHE: ~/.cache/opam1.2/cache
  OPAM_REPO: https://github.com/ocaml/opam-repository.git
  OPAM_TEST_REPO_SHA: 849d953adddc9c44486de3307e9c757aba85b225
  OPAM_REPO_SHA: 849d953adddc9c44486de3307e9c757aba85b225
  SOLVER:
  CYGWIN_MIRROR: http://mirrors.kernel.org/sourceware/cygwin/
  CYGWIN_ROOT: D:\cygwin
  CYGWIN: winsymlinks:native
  CYGWIN_EPOCH: 3

defaults:
  run:
    shell: bash

jobs:

####
# Compile doc
####
  Doc-Linux:
    runs-on: ubuntu-latest
    needs: [ Analyse ]
    strategy:
      matrix:
        ocamlv: [ 4.14.1 ]
      fail-fast: false
    env:
      OPAM_DOC: 1
    steps:
    - name: Install bubblewrap
      run: sudo apt install bubblewrap
    - name: Install man2html
      run: sudo apt install man2html
    - name: Checkout tree
      uses: actions/checkout@v3
    - name: Compile
      env:
        BASE_REF_SHA: ${{ github.event.pull_request.base.sha }}
        PR_REF_SHA: ${{ github.event.pull_request.head.sha }}
      run: bash -exu .github/scripts/main/main.sh x86_64-pc-linux-gnu
